name: cami_assembly
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - spades=3.13.1
  - megahit=1.2.7
  - ray=2.3.1
  - idba=1.1.3
  #- metavelvet=1.2.02
  #- metavelvet-sl=1.0
  - abyss=2.1.5